import { Text } from "@chakra-ui/react";

const InfoText = () => {
    return ( 

        <Text m="1rem">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet risus feugiat in ante. Amet venenatis urna cursus eget. Ipsum dolor sit amet consectetur adipiscing. Iaculis at erat pellentesque adipiscing commodo elit at. Orci eu lobortis elementum nibh tellus molestie nunc non. Velit scelerisque in dictum non consectetur a erat nam at. Feugiat vivamus at augue eget arcu dictum. Sed libero enim sed faucibus turpis in eu mi. Nunc mattis enim ut tellus elementum sagittis vitae et. Enim lobortis scelerisque fermentum dui. Faucibus scelerisque eleifend donec pretium vulputate. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Velit egestas dui id ornare arcu. Malesuada proin libero nunc consequat interdum varius sit. Neque ornare aenean euismod elementum nisi. Quam pellentesque nec nam aliquam sem et tortor. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Tellus elementum sagittis vitae et leo duis ut diam quam. At quis risus sed vulputate odio ut enim blandit.

Magnis dis parturient montes nascetur ridiculus mus mauris. Cursus euismod quis viverra nibh cras pulvinar. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Sem fringilla ut morbi tincidunt augue interdum velit. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Quam quisque id diam vel quam elementum pulvinar. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sed egestas egestas fringilla phasellus faucibus. Pellentesque massa placerat duis ultricies lacus. Diam sollicitudin tempor id eu nisl nunc. Mus mauris vitae ultricies leo integer.

Gravida in fermentum et sollicitudin ac orci phasellus egestas. Quis risus sed vulputate odio ut enim blandit volutpat. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Viverra maecenas accumsan lacus vel. Aliquet risus feugiat in ante metus dictum at tempor commodo. In hac habitasse platea dictumst. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Pretium fusce id velit ut tortor pretium. Tincidunt id aliquet risus feugiat in. Sed risus ultricies tristique nulla. Libero justo laoreet sit amet cursus. Euismod lacinia at quis risus sed. Convallis aenean et tortor at risus viverra adipiscing. Natoque penatibus et magnis dis parturient montes. Pellentesque elit ullamcorper dignissim cras tincidunt.

Diam phasellus vestibulum lorem sed risus ultricies. Vitae turpis massa sed elementum tempus. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Ut etiam sit amet nisl purus in mollis nunc sed. Dui faucibus in ornare quam viverra orci. Rhoncus urna neque viverra justo nec ultrices. Ipsum a arcu cursus vitae. A condimentum vitae sapien pellentesque habitant morbi tristique. Convallis posuere morbi leo urna molestie at. At risus viverra adipiscing at in. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Nec ultrices dui sapien eget mi proin sed.

Rutrum quisque non tellus orci ac auctor augue mauris augue. Lobortis scelerisque fermentum dui faucibus in. Ut placerat orci nulla pellentesque dignissim. Sed nisi lacus sed viverra tellus in hac habitasse platea. Nunc non blandit massa enim nec dui nunc mattis. Tempus urna et pharetra pharetra massa massa ultricies mi. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Suspendisse sed nisi lacus sed viverra tellus in hac. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Non sodales neque sodales ut etiam sit. Diam vel quam elementum pulvinar etiam non. Proin sed libero enim sed faucibus turpis. Elit duis tristique sollicitudin nibh sit. Amet justo donec enim diam vulputate ut pharetra sit amet. Nisl pretium fusce id velit ut tortor pretium. At urna condimentum mattis pellentesque id nibh. Consequat semper viverra nam libero justo laoreet sit. Faucibus turpis in eu mi bibendum neque egestas congue. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat.

Risus quis varius quam quisque. Senectus et netus et malesuada. Sed lectus vestibulum mattis ullamcorper velit. Est ultricies integer quis auctor elit sed vulputate mi. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Lorem ipsum dolor sit amet consectetur adipiscing. Vel elit scelerisque mauris pellentesque. Volutpat blandit aliquam etiam erat velit scelerisque. Leo integer malesuada nunc vel risus commodo. Nec dui nunc mattis enim ut tellus elementum. Ultrices eros in cursus turpis massa tincidunt dui ut. Auctor elit sed vulputate mi sit. Lectus magna fringilla urna porttitor rhoncus. Lectus arcu bibendum at varius. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. At tempor commodo ullamcorper a lacus vestibulum. Varius morbi enim nunc faucibus a pellentesque sit amet. Adipiscing at in tellus integer feugiat.

Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Augue neque gravida in fermentum et. Bibendum est ultricies integer quis auctor elit sed vulputate. Lacus vel facilisis volutpat est velit egestas. Eu mi bibendum neque egestas congue quisque egestas diam in. Augue ut lectus arcu bibendum. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Sit amet venenatis urna cursus eget nunc. Quis lectus nulla at volutpat. Tempor nec feugiat nisl pretium fusce id velit ut. Nascetur ridiculus mus mauris vitae ultricies leo integer. Ipsum suspendisse ultrices gravida dictum. Donec enim diam vulputate ut pharetra. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Viverra accumsan in nisl nisi scelerisque eu ultrices. Nisi est sit amet facilisis magna etiam. Magna ac placerat vestibulum lectus mauris. Amet justo donec enim diam vulputate ut pharetra sit. Quis blandit turpis cursus in hac habitasse.

Sit amet massa vitae tortor condimentum lacinia quis vel. Semper auctor neque vitae tempus quam pellentesque nec nam. Tellus pellentesque eu tincidunt tortor aliquam. Metus vulputate eu scelerisque felis. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Pellentesque habitant morbi tristique senectus et netus. Aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus. Scelerisque fermentum dui faucibus in ornare. At risus viverra adipiscing at in tellus integer feugiat scelerisque. Mattis pellentesque id nibh tortor. Amet justo donec enim diam vulputate ut pharetra sit. Nunc lobortis mattis aliquam faucibus. Venenatis cras sed felis eget velit aliquet sagittis id. Neque vitae tempus quam pellentesque nec nam. Tincidunt lobortis feugiat vivamus at. Tempus iaculis urna id volutpat lacus.

Non arcu risus quis varius quam quisque id. Lacus sed viverra tellus in hac. Nec feugiat in fermentum posuere urna nec. Tincidunt eget nullam non nisi est sit amet. A iaculis at erat pellentesque adipiscing commodo elit. Neque volutpat ac tincidunt vitae semper quis lectus. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Elementum pulvinar etiam non quam. Nisi porta lorem mollis aliquam ut porttitor. Faucibus turpis in eu mi bibendum. Pulvinar mattis nunc sed blandit libero. Euismod lacinia at quis risus sed vulputate odio ut enim. Eget lorem dolor sed viverra. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Nam libero justo laoreet sit. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Faucibus purus in massa tempor nec feugiat. Egestas integer eget aliquet nibh.

Diam sit amet nisl suscipit adipiscing. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. At volutpat diam ut venenatis tellus in metus vulputate eu. Cursus vitae congue mauris rhoncus aenean vel elit. Elit pellentesque habitant morbi tristique. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Id aliquet risus feugiat in ante metus dictum. Posuere urna nec tincidunt praesent semper feugiat. Mattis aliquam faucibus purus in massa tempor nec feugiat. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Mauris ultrices eros in cursus turpis massa tincidunt dui. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Ut porttitor leo a diam sollicitudin tempor. Lacinia at quis risus sed vulputate odio ut. Feugiat pretium nibh ipsum consequat nisl vel. Et netus et malesuada fames. Lectus proin nibh nisl condimentum. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus.

Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Pellentesque sit amet porttitor eget dolor morbi non. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Sed risus ultricies tristique nulla aliquet enim tortor at. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Tincidunt dui ut ornare lectus. Vulputate eu scelerisque felis imperdiet proin. Dictum varius duis at consectetur lorem. Sit amet tellus cras adipiscing. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Dignissim suspendisse in est ante in nibh. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Massa id neque aliquam vestibulum morbi blandit cursus risus. Viverra vitae congue eu consequat. Tempus urna et pharetra pharetra massa. Ut ornare lectus sit amet est placerat in egestas. Cras pulvinar mattis nunc sed blandit libero. Morbi blandit cursus risus at ultrices. Faucibus purus in massa tempor nec feugiat nisl. Vitae purus faucibus ornare suspendisse sed nisi lacus sed.

Id eu nisl nunc mi ipsum. Mauris nunc congue nisi vitae suscipit tellus mauris a. Tincidunt nunc pulvinar sapien et ligula. Mattis aliquam faucibus purus in massa tempor. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Porta lorem mollis aliquam ut. Cras ornare arcu dui vivamus arcu. Consequat ac felis donec et odio. Imperdiet nulla malesuada pellentesque elit eget gravida. Id porta nibh venenatis cras. Augue interdum velit euismod in pellentesque massa placerat duis. Est placerat in egestas erat imperdiet sed. Aliquet risus feugiat in ante metus. Aenean euismod elementum nisi quis eleifend quam. Faucibus et molestie ac feugiat. Ac felis donec et odio pellentesque.

Ultricies leo integer malesuada nunc vel risus commodo viverra. Tristique risus nec feugiat in. Tempus imperdiet nulla malesuada pellentesque elit. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Ornare suspendisse sed nisi lacus sed viverra tellus in. Ultricies integer quis auctor elit sed vulputate mi sit. Magna fringilla urna porttitor rhoncus dolor purus. Auctor eu augue ut lectus. Arcu ac tortor dignissim convallis aenean et. Praesent elementum facilisis leo vel. Id aliquet risus feugiat in ante metus dictum. Quis commodo odio aenean sed adipiscing diam donec. Id venenatis a condimentum vitae sapien. Vitae justo eget magna fermentum iaculis eu non. Nulla at volutpat diam ut venenatis tellus.

Volutpat consequat mauris nunc congue nisi vitae. Dictumst vestibulum rhoncus est pellentesque. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Cras ornare arcu dui vivamus. Pellentesque id nibh tortor id aliquet lectus. In ante metus dictum at. Nunc id cursus metus aliquam eleifend mi in. Ultrices vitae auctor eu augue ut lectus arcu. Nunc sed augue lacus viverra. Ut lectus arcu bibendum at varius vel pharetra. Felis eget nunc lobortis mattis aliquam faucibus purus in. Volutpat blandit aliquam etiam erat. Mi proin sed libero enim. Ut placerat orci nulla pellentesque dignissim enim sit amet. Sit amet cursus sit amet dictum sit amet justo donec. Cursus in hac habitasse platea dictumst quisque. Et egestas quis ipsum suspendisse ultrices gravida dictum. Mi eget mauris pharetra et ultrices neque ornare. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent.

Justo eget magna fermentum iaculis eu non. Quam id leo in vitae turpis massa sed. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Pharetra vel turpis nunc eget. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Morbi leo urna molestie at elementum eu facilisis. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Sit amet est placerat in egestas. At in tellus integer feugiat scelerisque varius morbi. Non tellus orci ac auctor augue.

Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Tincidunt ornare massa eget egestas purus. Fringilla ut morbi tincidunt augue interdum velit euismod in. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Arcu cursus euismod quis viverra. Sodales neque sodales ut etiam. Vitae et leo duis ut diam. Iaculis nunc sed augue lacus viverra vitae congue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Iaculis urna id volutpat lacus laoreet. Faucibus nisl tincidunt eget nullam. Integer vitae justo eget magna.

Orci dapibus ultrices in iaculis nunc sed augue lacus. In ante metus dictum at. Sagittis purus sit amet volutpat consequat. Sed risus ultricies tristique nulla aliquet enim tortor. Feugiat sed lectus vestibulum mattis ullamcorper. Id porta nibh venenatis cras sed. Adipiscing tristique risus nec feugiat in fermentum. Diam quam nulla porttitor massa id neque. Purus semper eget duis at tellus at urna condimentum mattis. Sit amet luctus venenatis lectus. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Aenean et tortor at risus viverra adipiscing at in.

Duis at consectetur lorem donec massa. Lectus quam id leo in vitae turpis massa. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Mauris ultrices eros in cursus turpis massa. In tellus integer feugiat scelerisque varius. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Auctor elit sed vulputate mi sit. Non diam phasellus vestibulum lorem sed risus. Sed felis eget velit aliquet sagittis id consectetur purus. At quis risus sed vulputate odio ut enim blandit. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada.

Semper auctor neque vitae tempus quam pellentesque. Eu feugiat pretium nibh ipsum consequat nisl vel. Id aliquet risus feugiat in ante metus dictum at tempor. Ac tortor dignissim convallis aenean et. Eget arcu dictum varius duis at consectetur. Facilisis leo vel fringilla est ullamcorper eget. Nisi porta lorem mollis aliquam ut porttitor leo a. Malesuada fames ac turpis egestas integer eget. At tellus at urna condimentum mattis pellentesque. Sem fringilla ut morbi tincidunt augue interdum. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat.

Euismod lacinia at quis risus. Tristique senectus et netus et malesuada. Pharetra convallis posuere morbi leo urna. Interdum consectetur libero id faucibus nisl tincidunt eget. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Nec ultrices dui sapien eget mi. Gravida arcu ac tortor dignissim convallis. Velit dignissim sodales ut eu sem integer vitae. Enim ut sem viverra aliquet eget sit. Neque volutpat ac tincidunt vitae semper quis. Magna sit amet purus gravida quis blandit turpis cursus. Amet tellus cras adipiscing enim. Ornare lectus sit amet est placerat in egestas erat. Pellentesque habitant morbi tristique senectus.
        </Text>

     );
}
 
export default InfoText;